# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/eros_/Downloads/TFMPedalMultiefectosI2S_OPT_FIFO/PROJECT/PROJECT.srcs/sources_1/ip/fifo_generator_test/fifo_generator_test.xci
# IP: The module: 'fifo_generator_test' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/eros_/Downloads/TFMPedalMultiefectosI2S_OPT_FIFO/PROJECT/PROJECT.srcs/sources_1/ip/fifo_generator_test/fifo_generator_test.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_test'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/eros_/Downloads/TFMPedalMultiefectosI2S_OPT_FIFO/PROJECT/PROJECT.srcs/sources_1/ip/fifo_generator_test/fifo_generator_test_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_test'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/eros_/Downloads/TFMPedalMultiefectosI2S_OPT_FIFO/PROJECT/PROJECT.srcs/sources_1/ip/fifo_generator_test/fifo_generator_test.xci
# IP: The module: 'fifo_generator_test' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/eros_/Downloads/TFMPedalMultiefectosI2S_OPT_FIFO/PROJECT/PROJECT.srcs/sources_1/ip/fifo_generator_test/fifo_generator_test.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_test'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/eros_/Downloads/TFMPedalMultiefectosI2S_OPT_FIFO/PROJECT/PROJECT.srcs/sources_1/ip/fifo_generator_test/fifo_generator_test_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_test'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
