# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config  -id {Coretcl 2-1488}  -string {{WARNING: [Coretcl 2-1488] Problem adding IP cache entry: Directory already exists: c:/Users/eros_/Downloads/TFMPedalMultiefectosI2S_OPT/PROJECT/PROJECT.cache/ip/2018.3/b5445c0930bba154}}  -suppress 
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/eros_/Downloads/TFMPedalMultiefectosI2S_OPT/PROJECT/PROJECT.cache/wt [current_project]
set_property parent.project_path C:/Users/eros_/Downloads/TFMPedalMultiefectosI2S_OPT/PROJECT/PROJECT.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Users/eros_/Downloads/TFMPedalMultiefectosI2S_OPT/PROJECT/PROJECT.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/eros_/Downloads/TFMPedalMultiefectosI2S_OPT/Detailed_Design/Digital_Efects/Compressor/EfectCOMPRESSOR.vhd
  C:/Users/eros_/Downloads/TFMPedalMultiefectosI2S_OPT/Detailed_Design/Digital_Efects/Filters/EfectoBankFilter.vhd
  C:/Users/eros_/Downloads/TFMPedalMultiefectosI2S_OPT/Detailed_Design/Packages/pkg_sine.vhd
  C:/Users/eros_/Downloads/TFMPedalMultiefectosI2S_OPT/Detailed_Design/Digital_Efects/Chorus/EfectoCHORUS.vhd
  C:/Users/eros_/Downloads/TFMPedalMultiefectosI2S_OPT/Detailed_Design/Digital_Efects/Delay/EfectoDELAY.vhd
  C:/Users/eros_/Downloads/TFMPedalMultiefectosI2S_OPT/Detailed_Design/Digital_Efects/Eco/EfectoECO.vhd
  C:/Users/eros_/Downloads/TFMPedalMultiefectosI2S_OPT/Detailed_Design/Digital_Efects/ES/EfectoES.vhd
  C:/Users/eros_/Downloads/TFMPedalMultiefectosI2S_OPT/Detailed_Design/Digital_Efects/Looper/EfectoLOOPER.vhd
  C:/Users/eros_/Downloads/TFMPedalMultiefectosI2S_OPT/Detailed_Design/Digital_Efects/Overdrive/EfectoOVERDRIVE.vhd
  C:/Users/eros_/Downloads/TFMPedalMultiefectosI2S_OPT/Detailed_Design/Digital_Efects/Reverb/EfectoREVERB.vhd
  C:/Users/eros_/Downloads/TFMPedalMultiefectosI2S_OPT/Detailed_Design/Digital_Efects/Reverb/EfectoREVERB_PARAMETRIZADO.vhd
  C:/Users/eros_/Downloads/TFMPedalMultiefectosI2S_OPT/Detailed_Design/Digital_Efects/Vibrato/EfectoVIBRATO.vhd
  C:/Users/eros_/Downloads/TFMPedalMultiefectosI2S_OPT/Detailed_Design/Digital_Efects/Filters/Fir_Filter_Autowah.vhd
  C:/Users/eros_/Downloads/TFMPedalMultiefectosI2S_OPT/Detailed_Design/Digital_Efects/Filters/Ruta_datos_FIR_WAH.vhd
  C:/Users/eros_/Downloads/TFMPedalMultiefectosI2S_OPT/Detailed_Design/Digital_Efects/Filters/controlador_fir_WAH.vhd
  C:/Users/eros_/Downloads/TFMPedalMultiefectosI2S_OPT/Detailed_Design/Packages/pkg_digital_effects.vhd
  C:/Users/eros_/Downloads/TFMPedalMultiefectosI2S_OPT/Detailed_Design/Digital_Efects/digital_efects.vhd
  C:/Users/eros_/Downloads/TFMPedalMultiefectosI2S_OPT/Detailed_Design/LEDs_Displays/display_counter.vhd
  C:/Users/eros_/Downloads/TFMPedalMultiefectosI2S_OPT/Detailed_Design/Packages/pkg_letters.vhd
  C:/Users/eros_/Downloads/TFMPedalMultiefectosI2S_OPT/Detailed_Design/LEDs_Displays/display_interface.vhd
  C:/Users/eros_/Downloads/TFMPedalMultiefectosI2S_OPT/Detailed_Design/LEDs_Displays/display_states.vhd
  C:/Users/eros_/Downloads/TFMPedalMultiefectosI2S_OPT/Detailed_Design/Packages/pkg_components.vhd
  C:/Users/eros_/Downloads/TFMPedalMultiefectosI2S_OPT/Detailed_Design/Driver_i2s/i2s_transceiver.vhd
  C:/Users/eros_/Downloads/TFMPedalMultiefectosI2S_OPT/Detailed_Design/LEDs_Displays/leds.vhd
  C:/Users/eros_/Downloads/TFMPedalMultiefectosI2S_OPT/Detailed_Design/Genericos/register.vhd
  C:/Users/eros_/Downloads/TFMPedalMultiefectosI2S_OPT/Detailed_Design/Genericos/sine_wave_2_55_hz.vhd
  C:/Users/eros_/Downloads/TFMPedalMultiefectosI2S_OPT/Detailed_Design/Genericos/sine_wave_5_1_hz.vhd
  C:/Users/eros_/Downloads/TFMPedalMultiefectosI2S_OPT/Detailed_Design/Top/i2s_playback.vhd
}
read_ip -quiet C:/Users/eros_/Downloads/TFMPedalMultiefectosI2S_OPT/PROJECT/PROJECT.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1.xci
set_property used_in_implementation false [get_files -all c:/Users/eros_/Downloads/TFMPedalMultiefectosI2S_OPT/PROJECT/PROJECT.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1_ooc.xdc]

read_ip -quiet C:/Users/eros_/Downloads/TFMPedalMultiefectosI2S_OPT/PROJECT/PROJECT.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1.xci
set_property used_in_implementation false [get_files -all c:/Users/eros_/Downloads/TFMPedalMultiefectosI2S_OPT/PROJECT/PROJECT.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/eros_/Downloads/TFMPedalMultiefectosI2S_OPT/PROJECT/PROJECT.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/eros_/Downloads/TFMPedalMultiefectosI2S_OPT/PROJECT/PROJECT.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/eros_/Downloads/TFMPedalMultiefectosI2S_OPT/Constrains/i2s_playback.xdc
set_property used_in_implementation false [get_files C:/Users/eros_/Downloads/TFMPedalMultiefectosI2S_OPT/Constrains/i2s_playback.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top i2s_playback -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef i2s_playback.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file i2s_playback_utilization_synth.rpt -pb i2s_playback_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
